### ISSUE TITLE
Enter Key does not copy to clipboard

### ISSUE THREAD

**Issue by Kitty131** [ethanpil/snips#2]
Dear Ethanpil - 

Thank you so much for snips.  

Hitting the enter key does not copy the selected snippet.  I have to mouse to the snippet and double click.  Would you know what the problem might be?  Thank you again.

**Comment by ethanpil** [comment]
Hi Kitty, I cannot reproduce this issue. Please try the latest release. If its still not working, what software are you pasting the snip into?
