### ISSUE TITLE
Pressing escape still (sometimes?) sends snippets 

### ISSUE THREAD

**Issue by jil24** [ethanpil/snips#3]
GuiEscape block needs a final "return" statement. Without it, pressing escape to dismiss the GUI still (if a snippet was previously sent from search results) sends snippets 

https://github.com/ethanpil/snips/blob/3745a7822531ed314d9524a9cf1c5aa9bca9d2b2/snips.ahk#L185

**Comment by ethanpil** [comment]
Thanks. Will get to this when I can, otherwise please feel free to submit PR and I will accept it.

**Comment by ethanpil** [comment]
Should be fixed in 80a2ccb7c3a7df3780181b4e967e93f1ff926aa7 and in next release.
